
name: Create Release

on:
  release:
    types:
      - created

jobs:
  release-zip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip . -x ".vscode/*" ".git/*" ".github/*" ".gitignore"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}